# Generated by Django 3.1.7 on 2021-04-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdascadastro',
            name='colheita_data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='evento_ocorrido',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='lavoura_tipo',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='loc',
            field=models.CharField(max_length=11, null=True, verbose_name='LAT, LNG'),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='nome',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
