# Generated by Django 3.1.7 on 2021-04-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroConflitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loclat', models.CharField(max_length=13, null=True, verbose_name='LAT')),
                ('loclng', models.CharField(max_length=13, null=True, verbose_name='LNG')),
                ('dist', models.FloatField()),
            ],
        ),
    ]
