# Generated by Django 3.1.7 on 2021-04-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdas', '0002_cadastroconflitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroconflitante',
            name='idConfl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
