# Generated by Django 3.1.7 on 2021-04-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdas', '0002_auto_20210403_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdascadastro',
            name='loc',
        ),
        migrations.AddField(
            model_name='perdascadastro',
            name='locLat',
            field=models.CharField(max_length=13, null=True, verbose_name='LAT'),
        ),
        migrations.AddField(
            model_name='perdascadastro',
            name='locLng',
            field=models.CharField(max_length=13, null=True, verbose_name='LNG'),
        ),
    ]
