# Generated by Django 3.1.7 on 2021-04-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdas', '0003_auto_20210404_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdascadastro',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='evento_ocorrido',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='lavoura_tipo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='locLat',
            field=models.CharField(max_length=13, verbose_name='LAT'),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='locLng',
            field=models.CharField(max_length=13, verbose_name='LNG'),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='nome',
            field=models.CharField(max_length=60),
        ),
    ]
