# Generated by Django 3.1.7 on 2021-04-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdas', '0004_auto_20210404_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdascadastro',
            name='locLat',
            field=models.CharField(max_length=13, null=True, verbose_name='LAT'),
        ),
        migrations.AlterField(
            model_name='perdascadastro',
            name='locLng',
            field=models.CharField(max_length=13, null=True, verbose_name='LNG'),
        ),
    ]
