# Generated by Django 3.1.7 on 2021-04-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perdas', '0005_auto_20210404_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perdascadastro',
            old_name='colheita_data',
            new_name='colheitaData',
        ),
        migrations.RenameField(
            model_name='perdascadastro',
            old_name='evento_ocorrido',
            new_name='eventoOcorrido',
        ),
        migrations.RenameField(
            model_name='perdascadastro',
            old_name='lavoura_tipo',
            new_name='lavouraTipo',
        ),
    ]
