# Generated by Django 3.1.7 on 2021-04-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perdas', '0006_auto_20210404_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perdascadastro',
            old_name='lavouraTipo',
            new_name='colheitaTipo',
        ),
    ]
