# Generated by Django 3.1.7 on 2021-04-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perdas', '0007_auto_20210404_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perdascadastro',
            old_name='colheitaData',
            new_name='colheitadata',
        ),
        migrations.RenameField(
            model_name='perdascadastro',
            old_name='colheitaTipo',
            new_name='colheitatipo',
        ),
        migrations.RenameField(
            model_name='perdascadastro',
            old_name='eventoOcorrido',
            new_name='eventoocorrido',
        ),
    ]
